let mockApartments = [
  {
    id: 1,
    name: "Octopus",
    street: "101 Paradise Road",
    unit: "1B",
    city: "Malé",
    state: "Maldives",
    square_footage: "1600",
    price: "1,225",
    bedrooms: 1,
    bathrooms: 1.0,
    pets: "no pets allowed",
    image:
      "https://images.unsplash.com/photo-1615571022219-eb45cf7faa9d?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    smart_security_system: true,
    rooftop_pool: true,
    golf_course: false,
    community_garden: false,
    keyless_entry: true,
    onsite_daycare: false,
    smart_thermostat: true,
    spa: true,
    concierge: true,
    ocean_view: true,
    personal_chef: false,
    fiber_optic: true,
    maid_service: false,
    pizza_ovens: false,
    hibachi_grill: false,
    full_kitchen: true,
    user_id: 1,
  },
  {
    id: 2,
    name: "Algae",
    street: "102 Utopia Highway",
    unit: "2D",
    city: "Hulhumalé",
    state: "Maldives",
    square_footage: "1700",
    price: "1,450",
    bedrooms: 2,
    bathrooms: 1.5,
    pets: "pets allowed",
    image:
      "https://images.unsplash.com/photo-1631528858266-5ebeb8bfc6f5?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D",
    smart_security_system: false,
    rooftop_pool: false,
    golf_course: true,
    community_garden: false,
    keyless_entry: true,
    onsite_daycare: true,
    smart_thermostat: true,
    spa: true,
    concierge: false,
    ocean_view: true,
    personal_chef: true,
    fiber_optic: false,
    maid_service: true,
    pizza_ovens: true,
    hibachi_grill: false,
    full_kitchen: false,
    user_id: 1,
  },
  {
    id: 2,
    name: "Treasure",
    street: "523 Luxury Blvd",
    unit: "9A",
    city: "Fuvahmulah",
    state: "Maldives",
    square_footage: "2400",
    price: "900",
    bedrooms: 3,
    bathrooms: 2.0,
    pets: "no pets allowed",
    image:
      "https://images.unsplash.com/photo-1613553497126-a44624272024?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D",
    smart_security_system: true,
    rooftop_pool: false,
    golf_course: false,
    community_garden: true,
    keyless_entry: false,
    onsite_daycare: true,
    smart_thermostat: false,
    spa: true,
    concierge: true,
    ocean_view: false,
    personal_chef: false,
    fiber_optic: true,
    maid_service: true,
    pizza_ovens: false,
    hibachi_grill: true,
    full_kitchen: false,
    user_id: 2,
  },
  {
    id: 3,
    name: "Lobster",
    street: "1017 Sunset Ln.",
    unit: "7C",
    city: "Addu City",
    state: "Maldives",
    square_footage: "2500",
    price: "1,650",
    bedrooms: 2,
    bathrooms: 1.5,
    pets: "pets allowed",
    image:
      "https://images.unsplash.com/photo-1511840636560-acee95b3a83f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D",
    smart_security_system: true,
    rooftop_pool: true,
    golf_course: false,
    community_garden: true,
    keyless_entry: false,
    onsite_daycare: true,
    smart_thermostat: true,
    spa: true,
    concierge: true,
    ocean_view: false,
    personal_chef: true,
    fiber_optic: true,
    maid_service: true,
    pizza_ovens: false,
    hibachi_grill: true,
    full_kitchen: false,
    user_id: 2,
  },
  {
    id: 4,
    name: "Sunscreen",
    street: "111 Sandy Court",
    unit: "5L",
    city: "Kulhudhuffushi",
    state: "Maldives",
    square_footage: "3000",
    price: "890",
    bedrooms: 2,
    bathrooms: 2.5,
    pets: "no pets allowed",
    image:
      "https://plus.unsplash.com/premium_photo-1684348962187-988fc3d7f024?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGJlYWNoJTIwaG91c2V8ZW58MHx8MHx8fDA%3D",
    smart_security_system: true,
    rooftop_pool: true,
    golf_course: true,
    community_garden: true,
    keyless_entry: true,
    onsite_daycare: true,
    smart_thermostat: true,
    spa: true,
    concierge: false,
    ocean_view: false,
    personal_chef: false,
    fiber_optic: false,
    maid_service: true,
    pizza_ovens: false,
    hibachi_grill: true,
    full_kitchen: true,
    user_id: 2,
  },
  {
    id: 5,
    name: "Bubble",
    street: "211 Forrest Bridge",
    unit: "3K",
    city: "Thinadhoo",
    state: "Maldives",
    square_footage: "1100",
    price: "2,100",
    bedrooms: 1,
    bathrooms: 1.5,
    pets: "pets allowed",
    image:
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    smart_security_system: true,
    rooftop_pool: true,
    golf_course: false,
    community_garden: true,
    keyless_entry: true,
    onsite_daycare: false,
    smart_thermostat: false,
    spa: true,
    concierge: false,
    ocean_view: true,
    personal_chef: true,
    fiber_optic: false,
    maid_service: true,
    pizza_ovens: false,
    hibachi_grill: true,
    full_kitchen: false,
    user_id: 1,
  },
]

export default mockApartments
